#if !defined(INCLUDE_ARRAY_MACROS_FLUID_SRCUX_H)
#define INCLUDE_ARRAY_MACROS_FLUID_SRCUX_H

// This file is generated by tools/define_arrays.py

#if NDIMS == 2
// [2 : isize+0], [1 : jsize+0]
#define SRCUX(I, J) (srcux[(I-2) + (isize-1) * (J-1)])
#define SRCUX_NADDS (int [NDIMS][2]){ {-1, 0}, {0, 0}, }
#endif

#if NDIMS == 3
// [2 : isize+0], [1 : jsize+0], [1 : ksize+0]
#define SRCUX(I, J, K) (srcux[(I-2) + (isize-1) * ((J-1) + (jsize+0) * (K-1))])
#define SRCUX_NADDS (int [NDIMS][2]){ {-1, 0}, {0, 0}, {0, 0}, }
#endif

#endif // INCLUDE_ARRAY_MACROS_FLUID_SRCUX_H
