#if !defined(INCLUDE_ARRAY_MACROS_FLUID_UY_H)
#define INCLUDE_ARRAY_MACROS_FLUID_UY_H

// This file is generated by tools/define_arrays.py

// [0 : isize+1], [0 : jsize+1]
#define UY(I, J) (uy[(I  ) + (isize+2) * (J  )])
#define UY_NADDS (int [NDIMS][2]){ {1, 1}, {1, 1}, }

#endif // INCLUDE_ARRAY_MACROS_FLUID_UY_H
