#if !defined(INCLUDE_ARRAY_MACROS_DOMAIN_DXC_H)
#define INCLUDE_ARRAY_MACROS_DOMAIN_DXC_H

// This file is generated by tools/define_arrays.py

// [1 : isize+1]
#define DXC(I) (dxc[(I-1)])
#define DXC_NADDS (int [2]){0, 1}

#endif // INCLUDE_ARRAY_MACROS_DOMAIN_DXC_H
