#if !defined(INCLUDE_ARRAY_MACROS_DOMAIN_DXF_H)
#define INCLUDE_ARRAY_MACROS_DOMAIN_DXF_H

// This file is generated by tools/define_arrays.py

// [1 : isize+0]
#define DXF(I) (dxf[(I-1)])
#define DXF_NADDS (int [2]){0, 0}

#endif // INCLUDE_ARRAY_MACROS_DOMAIN_DXF_H
