#if !defined(INCLUDE_ARRAY_MACROS_DOMAIN_HXXC_H)
#define INCLUDE_ARRAY_MACROS_DOMAIN_HXXC_H

// This file is generated by tools/define_arrays.py

// [1 : isize+0]
#define HXXC(I) (hxxc[(I-1)])
#define HXXC_NADDS (int [2]){0, 0}

#endif // INCLUDE_ARRAY_MACROS_DOMAIN_HXXC_H
