#if !defined(INCLUDE_ARRAY_MACROS_DOMAIN_HXXF_H)
#define INCLUDE_ARRAY_MACROS_DOMAIN_HXXF_H

// This file is generated by tools/define_arrays.py

// [1 : isize+1]
#define HXXF(I) (hxxf[(I-1)])
#define HXXF_NADDS (int [2]){0, 1}

#endif // INCLUDE_ARRAY_MACROS_DOMAIN_HXXF_H
