#if !defined(INCLUDE_ARRAY_MACROS_DOMAIN_JDXC_H)
#define INCLUDE_ARRAY_MACROS_DOMAIN_JDXC_H

// This file is generated by tools/define_arrays.py

// [1 : isize+0]
#define JDXC(I) (jdxc[(I-1)])
#define JDXC_NADDS (int [2]){0, 0}

#endif // INCLUDE_ARRAY_MACROS_DOMAIN_JDXC_H
