#if !defined(INCLUDE_ARRAY_MACROS_DOMAIN_JDXF_H)
#define INCLUDE_ARRAY_MACROS_DOMAIN_JDXF_H

// This file is generated by tools/define_arrays.py

// [1 : isize+1]
#define JDXF(I) (jdxf[(I-1)])
#define JDXF_NADDS (int [2]){0, 1}

#endif // INCLUDE_ARRAY_MACROS_DOMAIN_JDXF_H
