#if !defined(INCLUDE_ARRAY_MACROS_DOMAIN_XC_H)
#define INCLUDE_ARRAY_MACROS_DOMAIN_XC_H

// This file is generated by tools/define_arrays.py

// [0 : isize+1]
#define XC(I) (xc[(I  )])
#define XC_NADDS (int [2]){1, 1}

#endif // INCLUDE_ARRAY_MACROS_DOMAIN_XC_H
