#if !defined(INCLUDE_ARRAY_MACROS_DOMAIN_XF_H)
#define INCLUDE_ARRAY_MACROS_DOMAIN_XF_H

// This file is generated by tools/define_arrays.py

// [1 : isize+1]
#define XF(I) (xf[(I-1)])
#define XF_NADDS (int [2]){0, 1}

#endif // INCLUDE_ARRAY_MACROS_DOMAIN_XF_H
