#if !defined(INCLUDE_ARRAY_MACROS_STATISTICS_UX2_H)
#define INCLUDE_ARRAY_MACROS_STATISTICS_UX2_H

// This file is generated by tools/define_arrays.py

#if NDIMS == 2
// [1 : isize+1], [1 : jsize+0]
#define UX2(I, J) (ux2[(I-1) + (isize+1) * (J-1)])
#define UX2_NADDS (int [NDIMS][2]){ {0, 1}, {0, 0}, }
#endif

#if NDIMS == 3
// [1 : isize+1], [1 : jsize+0], [1 : ksize+0]
#define UX2(I, J, K) (ux2[(I-1) + (isize+1) * ((J-1) + (jsize+0) * (K-1))])
#define UX2_NADDS (int [NDIMS][2]){ {0, 1}, {0, 0}, {0, 0}, }
#endif

#endif // INCLUDE_ARRAY_MACROS_STATISTICS_UX2_H
