#if !defined(INCLUDE_ARRAY_MACROS_STATISTICS_UZ1_H)
#define INCLUDE_ARRAY_MACROS_STATISTICS_UZ1_H

// This file is generated by tools/define_arrays.py

#endif // INCLUDE_ARRAY_MACROS_STATISTICS_UZ1_H
